### ISSUE TITLE
User Table: Add Kobo Password

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/tech-dashboard#237]
To the user authentication can we add a column for their Kobo Password?
Then we can display this password in their dashboard

**Comment by brianwdavis** [comment]
This is a top priority unrelated to enrollment.

**Comment by brianwdavis** [comment]
Need to display this to the user in their "about me" page that shows their permissions. Don't need to worry about it being encrypted or salted or hashed, because it's not "secure" data.

This is actually an additional table with one row per "affiliation" and a column for the password. Then when a user logs in, you check what affiliations they have access to and show those passwords.

**Comment by saseehav** [comment]
table 'kobo_passwords' created in raw_db. 9/16/2020. 
For the tech dashboard still need to link user table column state to state in kobo_passwords table.

**Comment by brianwdavis** [comment]
look up `state` in `users` to get list of allowed states, then pull matching rows from `kobo_passwords` in the profile/login page for each user.

Edge cases!

 - If `all` show all rows

 - If `default` show no rows

Can be a very simple element on the page like "Kobo AL password: `blahblahblah`"
