### ISSUE TITLE
make decomp bags more like water sensors

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/tech-dashboard#820]
- filter by affiliation, year
- allow search by farm code
- choose a farm code
- fetch data for that farm code and display it how the table currently is instead of all farm codes

**Comment by brianwdavis** [comment]
Reviewing the state of this fix on the dev PR into prod:

![image](https://user-images.githubusercontent.com/13338560/157717606-212d58c8-e2f0-4ead-81aa-41a10bd9098f.png)

- There needs to be a back button at the top of an individual page that returns the user to the previous page **with the correct year still selected**. The browser back button defaults to showing the most recent year. (Medium priority)
 
- There should be affiliation chips on the main landing page to filter like all the other components. (Low priority)
 
- All rows should be shown on the individual page (24 instead of the default 20 shown in the screenshot). (High priority)

**Comment by mikahpinegar** [comment]
we can set it up so the browser back works using `history.push(location, <state values>)` and then extracting it at the previous page. we do it in most of the other pages that have a logical back where we want to remember state. we also still have the back button though for the other pages

**Comment by dearpriyankasa** [comment]
Ok, will look into it

**Comment by dearpriyankasa** [comment]
There needs to be a back button at the top of an individual page that returns the user to the previous page with the correct year still selected. The browser back button defaults to showing the most recent year. (Medium priority): DONE

There should be affiliation chips on the main landing page to filter like all the other components. (Low priority): DONE

All rows should be shown on the individual page (24 instead of the default 20 shown in the screenshot). (High priority): DONE
